version: '3.8'

services:
  hosting:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      
  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: bash -c "alembic upgrade head && uvicorn api.api:app --host 0.0.0.0 --port 8080 --reload"
    depends_on:
      - hosting
      
  pgadmin:
    container_name: pgadmin2
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5000:80"
    depends_on:
      - hosting